name: Checks the proto changes and release
'on':
  push:
    branches:
      - main
    paths:
      - protos/proto/aptos/transaction/v1/transaction.proto
  pull_request:
    branches:
      - main
    paths:
      - protos/proto/aptos/transaction/v1/transaction.proto

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install buf, which we use to generate code from the protos for Rust and TS.
      - name: Install buf
        uses: bufbuild/buf-setup-action@v1.24.0
        with:
          version: 1.28.1
    
      - name: Check the format of the proto files
        run: |
          set -e
          buf format -d aptos/transaction/v1/transaction.proto --exit-code
        working-directory: protos/proto
      - name: Capture the commit hash
        id: commit_hash
        run: |
          # Echo the commit hash to the output
          echo "::set-output name=commit_hash::$(echo $GITHUB_SHA)"
          # Echo the PR branch name to the output
          echo "::set-output name=branch_name::${{ github.head_ref }}"
      - name: Dispatch Event to SDK Repo
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          token: ${{ secrets.CI_TOKEN }}
          repository: 'larry-aptos/aptos-indexer-processor-sdk'
          event-type: 'proto-dependency-update'
          client-payload: '{"commit_hash": "${{ github.sha }}", "branch_name": "${{ steps.commit_hash.outputs.branch_name }}"}'
